frr version 10.7.1
frr defaults traditional
hostname cpe-isp2
log syslog informational
!
interface eth1
 description WAN HACIA AS200-PE1
 ip address 192.0.2.6/30
 ipv6 address 2001:db8:200:10::2/64
exit
!
interface eth2
 description LAN EMPRESARIAL
 ip address 10.30.0.3/24
 ipv6 address 2001:db8:30::3/64
exit
!
ip route 0.0.0.0/0 192.0.2.5
ipv6 route ::/0 2001:db8:200:10::1
!
router bgp 65002
 bgp router-id 192.0.2.6
 no bgp default ipv4-unicast
 neighbor 2001:db8:200:10::1 remote-as 200
 neighbor 2001:db8:200:10::1 description AS200-PE1
 !
 address-family ipv6 unicast
  network 2001:db8:30::/64
  neighbor 2001:db8:200:10::1 activate
  neighbor 2001:db8:200:10::1 route-map ISP2-IN-V6 in
  neighbor 2001:db8:200:10::1 route-map EMPRESA-OUT-V6 out
 exit-address-family
exit
!
!
ipv6 prefix-list EMPRESA-OUT-V6 seq 10 permit 2001:db8:30::/64
!
route-map EMPRESA-OUT-V6 permit 10
 match ipv6 address prefix-list EMPRESA-OUT-V6
exit
!
route-map ISP2-IN-V6 deny 10
exit
!
