global_defs {
    router_id CPE_ISP2
    script_user root
    enable_script_security
}

vrrp_script comprobar_wan {
    script "/usr/local/bin/check-wan.sh"
    interval 2
    timeout 1
    fall 2
    rise 2
}

vrrp_instance LAN_IPV4 {
    state BACKUP
    interface eth2
    virtual_router_id 30
    priority 100
    advert_int 1

    authentication {
        auth_type PASS
        auth_pass TLN03v4
    }

    track_interface {
        eth1
    }

    track_script {
        comprobar_wan
    }

    virtual_ipaddress {
        10.30.0.1/24 dev eth2
    }
}

vrrp_instance LAN_IPV6 {
    state BACKUP
    interface eth2
    virtual_router_id 31
    priority 100
    advert_int 1
    native_ipv6

    track_interface {
        eth1
    }

    track_script {
        comprobar_wan
    }

    virtual_ipaddress {
        2001:db8:30::1/64 dev eth2
    }
}
