frr version 10.7.1
frr defaults traditional
hostname as100-pe2
log syslog informational
!
interface eth1
 ip address 10.0.0.1/30
 ip ospf network point-to-point
 ip ospf prefix-suppression
 ipv6 ospf6 area 0
 ipv6 ospf6 network point-to-point
exit
!
interface eth2
 ip address 10.0.0.5/30
 ip ospf network point-to-point
 ip ospf prefix-suppression
 ipv6 ospf6 area 0
 ipv6 ospf6 network point-to-point
exit
!
interface lo
 ip address 172.16.1.2/32
 ipv6 address fc10:16:1::2/128
 ipv6 ospf6 area 0
 ipv6 ospf6 network point-to-point
exit
!
router bgp 100
 bgp router-id 172.16.1.2
 no bgp default ipv4-unicast
 neighbor 172.16.3.1 remote-as 100
 neighbor 172.16.3.1 update-source lo
 neighbor 172.16.3.2 remote-as 100
 neighbor 172.16.3.2 update-source lo
 neighbor fc10:16:3::1 remote-as 100
 neighbor fc10:16:3::1 update-source lo
 neighbor fc10:16:3::2 remote-as 100
 neighbor fc10:16:3::2 update-source lo
 !
 address-family ipv4 unicast
  neighbor 172.16.3.1 activate
  neighbor 172.16.3.2 activate
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor fc10:16:3::1 activate
  neighbor fc10:16:3::2 activate
 exit-address-family
exit
!
router ospf
 ospf router-id 172.16.1.2
 network 10.0.0.0/30 area 0
 network 10.0.0.4/30 area 0
 network 172.16.1.2/32 area 0
exit
!
router ospf6
exit
!
