frr version 10.7.1
frr defaults traditional
hostname as200-p5
log syslog informational
!
interface eth1
 ip address 10.0.0.45/30
 ip router isis AS200
 ipv6 router isis AS200
 isis network point-to-point
 isis circuit-type level-2-only
exit
!
interface eth2
 ip address 10.0.0.10/30
 ip router isis AS200
 ipv6 router isis AS200
 isis network point-to-point
 isis circuit-type level-2-only
exit
!
interface eth3
 ip address 10.0.0.49/30
 ip router isis AS200
 ipv6 router isis AS200
 isis network point-to-point
 isis circuit-type level-2-only
exit
!
interface eth4
 ip address 10.0.0.2/30
 ip router isis AS200
 ipv6 router isis AS200
 isis network point-to-point
 isis circuit-type level-2-only
exit
!
interface lo
 ip address 172.16.4.5/32
 ipv6 address fc10:16:4::5/128
 ip router isis AS200
 ipv6 router isis AS200
 isis passive
exit
!
!
router isis AS200
 net 49.0200.0000.0000.0205.00
 is-type level-2-only
 metric-style wide
 topology ipv6-unicast
exit
!
