frr version 10.7.1
frr defaults traditional
hostname as200-p5
log syslog informational
!
interface eth1
 ip address 10.0.0.45/30
exit
!
interface eth2
 ip address 10.0.0.10/30
exit
!
interface eth3
 ip address 10.0.0.49/30
exit
!
interface eth4
 ip address 10.0.0.2/30
exit
!
interface lo
 ip address 172.16.4.5/32
 ipv6 address fc10:16:4::5/128
exit
!