frr version 10.7.1
frr defaults traditional
hostname as200-borde2
log syslog informational
!
interface eth1
 ipv6 address 2001:db8:100:202::2/64
 ip address 161.0.1.2/30
exit
!
interface eth2
 ipv6 address 2001:db8:100:204::2/64
 ip address 181.0.0.2/30
exit
!
interface eth3
 ip address 10.0.0.58/30
 ip router isis AS200
 ipv6 router isis AS200
 isis network point-to-point
 isis circuit-type level-2-only
exit
!
interface lo
 ip address 190.1.1.2/32
 ipv6 address 2006:1:1::2/128
 ip router isis AS200
 ipv6 router isis AS200
 isis passive
exit
!
!
router isis AS200
 net 49.0200.0000.0000.0232.00
 is-type level-2-only
 metric-style wide
 topology ipv6-unicast
exit
!
!
router bgp 200
 bgp router-id 190.1.1.2
 no bgp default ipv4-unicast
 neighbor 161.0.1.1 remote-as 100
 neighbor 161.0.1.1 description eBGP enlace eth1
 neighbor 181.0.0.1 remote-as 100
 neighbor 181.0.0.1 description eBGP enlace eth2
 neighbor 2001:db8:100:202::1 remote-as 100
 neighbor 2001:db8:100:202::1 description eBGP IPv6 enlace eth1
 neighbor 2001:db8:100:204::1 remote-as 100
 neighbor 2001:db8:100:204::1 description eBGP IPv6 enlace eth2
 neighbor 172.16.3.1 remote-as 200
 neighbor 172.16.3.1 update-source lo
 neighbor 172.16.3.2 remote-as 200
 neighbor 172.16.3.2 update-source lo
 neighbor fc10:16:3::1 remote-as 200
 neighbor fc10:16:3::1 update-source lo
 neighbor fc10:16:3::2 remote-as 200
 neighbor fc10:16:3::2 update-source lo
 !
 address-family ipv4 unicast
  network 190.1.1.2/32
  neighbor 172.16.3.1 next-hop-self
  neighbor 172.16.3.2 next-hop-self
  neighbor 161.0.1.1 activate
  neighbor 161.0.1.1 route-map EBGP-IN-V4 in
  neighbor 161.0.1.1 route-map EBGP-OUT-V4 out
  neighbor 181.0.0.1 activate
  neighbor 181.0.0.1 route-map EBGP-IN-V4 in
  neighbor 181.0.0.1 route-map EBGP-OUT-V4 out
  neighbor 172.16.3.1 activate
  neighbor 172.16.3.2 activate
 exit-address-family
 !
 address-family ipv6 unicast
  network 2006:1:1::2/128
  neighbor fc10:16:3::1 next-hop-self
  neighbor fc10:16:3::2 next-hop-self
  neighbor 2001:db8:100:202::1 activate
  neighbor 2001:db8:100:202::1 route-map EBGP-IN-V6 in
  neighbor 2001:db8:100:202::1 route-map EBGP-OUT-V6 out
  neighbor 2001:db8:100:204::1 activate
  neighbor 2001:db8:100:204::1 route-map EBGP-IN-V6 in
  neighbor 2001:db8:100:204::1 route-map EBGP-OUT-V6 out
  neighbor fc10:16:3::1 activate
  neighbor fc10:16:3::2 activate
 exit-address-family
exit
!
!
ip prefix-list FROM-AS100-V4 seq 10 permit 200.1.1.0/24 le 32
ip prefix-list TO-AS100-V4 seq 10 permit 190.1.1.0/24 le 32
ipv6 prefix-list FROM-AS100-V6 seq 10 permit 2001:1:1::/48 le 128
ipv6 prefix-list TO-AS100-V6 seq 10 permit 2006:1:1::/48 le 128
!
route-map EBGP-IN-V4 permit 10
 match ip address prefix-list FROM-AS100-V4
exit
!
route-map EBGP-OUT-V4 permit 10
 match ip address prefix-list TO-AS100-V4
exit
!
route-map EBGP-IN-V6 permit 10
 match ipv6 address prefix-list FROM-AS100-V6
exit
!
route-map EBGP-OUT-V6 permit 10
 match ipv6 address prefix-list TO-AS100-V6
exit
!
ip prefix-list FROM-AS100-V4 seq 20 permit 192.0.2.0/30
ip prefix-list FROM-AS100-V4 seq 30 permit 203.0.113.0/24
ip prefix-list TO-AS100-V4 seq 20 permit 192.0.2.4/30
ipv6 prefix-list FROM-AS100-V6 seq 20 permit 2001:db8:30::/64
ipv6 prefix-list FROM-AS100-V6 seq 30 permit 2001:db8:500::/64
ipv6 prefix-list TO-AS100-V6 seq 20 permit 2001:db8:30::/64
