frr version 10.7.1
frr defaults traditional
hostname as200-pe1
log syslog informational
!
interface eth1
 ip address 10.0.0.53/30
 ip router isis AS200
 ipv6 router isis AS200
 isis network point-to-point
 isis circuit-type level-2-only
exit
!
interface eth2
 ip address 10.0.0.50/30
 ip router isis AS200
 ipv6 router isis AS200
 isis network point-to-point
 isis circuit-type level-2-only
exit
!
interface lo
 ip address 172.16.1.1/32
 ipv6 address fc10:16:1::1/128
 ip router isis AS200
 ipv6 router isis AS200
 isis passive
exit
!
!
router isis AS200
 net 49.0200.0000.0000.0221.00
 is-type level-2-only
 metric-style wide
 topology ipv6-unicast
exit
!
!
router bgp 200
 bgp router-id 172.16.1.1
 no bgp default ipv4-unicast
 neighbor 172.16.3.1 remote-as 200
 neighbor 172.16.3.1 update-source lo
 neighbor 172.16.3.2 remote-as 200
 neighbor 172.16.3.2 update-source lo
 neighbor fc10:16:3::1 remote-as 200
 neighbor fc10:16:3::1 update-source lo
 neighbor fc10:16:3::2 remote-as 200
 neighbor fc10:16:3::2 update-source lo
 !
 address-family ipv4 unicast
  neighbor 172.16.3.1 activate
  neighbor 172.16.3.2 activate
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor fc10:16:3::1 activate
  neighbor fc10:16:3::2 activate
 exit-address-family
exit
!
