frr version 10.7.1
frr defaults traditional
hostname as200-pe1
log syslog informational
!
interface eth1
 ip address 10.0.0.53/30
 ip router isis AS200
 ipv6 router isis AS200
 isis network point-to-point
 isis circuit-type level-2-only
exit
!
interface eth2
 ip address 10.0.0.50/30
 ip router isis AS200
 ipv6 router isis AS200
 isis network point-to-point
 isis circuit-type level-2-only
exit
!
interface lo
 ip address 172.16.1.1/32
 ipv6 address fc10:16:1::1/128
 ip router isis AS200
 ipv6 router isis AS200
 isis passive
exit
!
!
router isis AS200
 net 49.0200.0000.0000.0221.00
 is-type level-2-only
 metric-style wide
 topology ipv6-unicast
exit
!
!
interface eth3
 description ACCESO CPE-ISP2
 ip address 192.0.2.5/30
 ipv6 address 2001:db8:200:10::1/64
exit
!
router bgp 200
 bgp router-id 172.16.1.1
 no bgp default ipv4-unicast
 neighbor 172.16.3.1 remote-as 200
 neighbor 172.16.3.1 update-source lo
 neighbor 172.16.3.2 remote-as 200
 neighbor 172.16.3.2 update-source lo
 neighbor fc10:16:3::1 remote-as 200
 neighbor fc10:16:3::1 update-source lo
 neighbor fc10:16:3::2 remote-as 200
 neighbor fc10:16:3::2 update-source lo
 neighbor 2001:db8:200:10::2 remote-as 65002
 neighbor 2001:db8:200:10::2 description CPE-ISP2
 !
 address-family ipv4 unicast
  network 192.0.2.4/30
  neighbor 172.16.3.1 next-hop-self
  neighbor 172.16.3.2 next-hop-self
  neighbor 172.16.3.1 activate
  neighbor 172.16.3.2 activate
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor fc10:16:3::1 next-hop-self
  neighbor fc10:16:3::2 next-hop-self
  neighbor 2001:db8:200:10::2 activate
  neighbor 2001:db8:200:10::2 route-map CPE2-IN-V6 in
  neighbor 2001:db8:200:10::2 route-map CPE2-OUT-V6 out
  neighbor 2001:db8:200:10::2 maximum-prefix 1
  neighbor fc10:16:3::1 activate
  neighbor fc10:16:3::2 activate
 exit-address-family
exit
!
ipv6 prefix-list CPE2-IN-V6 seq 10 permit 2001:db8:30::/64
!
route-map CPE2-IN-V6 permit 10
 match ipv6 address prefix-list CPE2-IN-V6
exit
!
!
route-map CPE2-OUT-V6 deny 10
exit
!
