frr version 10.7.1
frr defaults traditional
hostname as200-p4
log syslog informational
!
interface eth1
 ip address 10.0.0.42/30
exit
!
interface eth2
 ip address 10.0.0.46/30
exit
!
interface eth3
 ip address 10.0.0.26/30
exit
!
interface eth4
 ip address 10.0.0.54/30
exit
!
interface eth5
 ip address 10.0.0.57/30
exit
!
interface lo
 ip address 172.16.4.4/32
 ipv6 address fc10:16:4::4/128
exit
!