frr version 10.7.1
frr defaults traditional
hostname as200-p3
log syslog informational
!
interface eth1
 ip address 10.0.0.30/30
exit
!
interface eth2
 ip address 10.0.0.41/30
exit
!
interface eth3
 ip address 10.0.0.38/30
exit
!
interface eth4
 ip address 10.0.0.61/30
exit
!
interface lo
 ip address 172.16.4.3/32
 ipv6 address fc10:16:4::3/128
exit
!