frr version 10.7.1
frr defaults traditional
hostname as200-borde1
log syslog informational
!
interface eth1
 ip address 161.0.0.2/30
exit
!
interface eth2
 ip address 181.0.1.2/30
exit
!
interface eth3
 ip address 10.0.0.62/30
 exit
!
interface lo
 ip address 190.1.1.1/32
 exit
!
